---
kind: pipeline
name: int-pgsql-chat
services:
- image: ghcr.io/nextcloud/continuous-integration-redis:latest
  name: cache
- environment:
    POSTGRES_DB: oc_autotest
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: owncloud
    POSTGRES_USER: oc_autotest
  image: ghcr.io/nextcloud/continuous-integration-postgres-13:postgres-13
  name: pgsql
  tmpfs:
  - /var/lib/postgresql/data
steps:
- commands:
  - bash tests/drone-run-integration-tests.sh || exit 0
  - composer --version
  - composer self-update --2
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DATABASEHOST
  - cd ../server
  - cd apps/$APP_NAME
  - composer install --no-dev
  - cd ../..
  - ./occ app:enable $APP_NAME
  - git clone --depth 1 -b $NOTIFICATIONS_BRANCH https://github.com/nextcloud/notifications
    apps/notifications
  - ./occ app:enable notifications
  - cd apps/$APP_NAME/tests/integration/
  - bash run.sh features/chat/mentions.feature
  environment:
    APP_NAME: spreed
    CORE_BRANCH: master
    DATABASEHOST: pgsql
    GUESTS_BRANCH: master
    NOTIFICATIONS_BRANCH: master
  image: ghcr.io/nextcloud/continuous-integration-php8.2:latest
  name: integration-chat
trigger:
  branch:
  - master
  - stable*
  event:
  - pull_request
  - push
