/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/recording/backend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update the recording status as a backend */
        post: operations["recording-backend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/recording/{token}/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Store the recording
         * @description When a `fileName` is provided the recording is expected to have been uploaded already through a share requested with {@see self::requestUpload()}, and only the post-processing is run. Otherwise the recording is read from the multipart `file` upload.
         *     Required capability: `recording-v1`
         */
        post: operations["recording-store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/recording/{token}/request-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a temporary upload share for a recording
         * @description Creates a password-protected public link share with create-only permissions on the per-room recording folder, so the recording backend can upload a large recording via the chunked public WebDAV API.
         *     Chunked uploading works the same way as it does for clients, documented in https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html#chunked-upload-v2
         *     - Base URL: `public.php/dav/uploads/$SHARETOKEN` - HTTP user: share token - HTTP password: share password
         *     After the upload and assembling is finished call the `/api/{apiVersion}/recording/{token}/store` endpoint {@see self::store()} and provide the file name, to trigger the notification for the moderator.
         *     Required capability: `recording-chunked-upload`
         */
        post: operations["recording-request-upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Capabilities: {
            features: string[];
            "features-local": string[];
            config: {
                attachments: {
                    allowed: boolean;
                    folder?: string;
                };
                call: {
                    enabled: boolean;
                    "breakout-rooms": boolean;
                    recording: boolean;
                    /** Format: int64 */
                    "recording-consent": number;
                    "supported-reactions": string[];
                    /** @description List of file names relative to the spreed/img/backgrounds/ web path, e.g. `2_home.jpg` */
                    "predefined-backgrounds": string[];
                    /** @description List of file paths relative to the server web root with leading slash, e.g. `/apps/spreed/img/backgrounds/2_home.jpg` */
                    "predefined-backgrounds-v2": string[];
                    "can-upload-background": boolean;
                    "sip-enabled": boolean;
                    "sip-dialout-enabled": boolean;
                    "default-phone-region": string;
                    "can-enable-sip": boolean;
                    "start-without-media": boolean;
                    /** Format: int64 */
                    "max-duration": number;
                    "blur-virtual-background": boolean;
                    "end-to-end-encryption": boolean;
                    "live-transcription": boolean;
                    "play-sounds": boolean;
                    /** Format: int64 */
                    "grid-limit": number;
                    "grid-limit-enforced": boolean;
                    /** @description URL of an external call service if one is used */
                    "external-call-service"?: string;
                };
                chat: {
                    /** Format: int64 */
                    "max-length": number;
                    /** Format: int64 */
                    "read-privacy": number;
                    "has-translation-providers": boolean;
                    "has-translation-task-providers": boolean;
                    /** Format: int64 */
                    "typing-privacy": number;
                    /** Format: int64 */
                    "summary-threshold": number;
                    "matterbridge-enabled": boolean;
                };
                conversations: {
                    "can-create": boolean;
                    "force-passwords": boolean;
                    /** @enum {string} */
                    "list-style": "two-lines" | "compact";
                    /** Format: int64 */
                    "description-length": number;
                    /** Format: int64 */
                    "retention-event": number;
                    /** Format: int64 */
                    "retention-phone": number;
                    /** Format: int64 */
                    "retention-instant-meetings": number;
                };
                federation: {
                    enabled: boolean;
                    "incoming-enabled": boolean;
                    "outgoing-enabled": boolean;
                    "only-trusted-servers": boolean;
                };
                previews: {
                    /** Format: int64 */
                    "max-gif-size": number;
                };
                signaling: {
                    /** Format: int64 */
                    "session-ping-limit": number;
                    /** @enum {string} */
                    mode: "internal" | "external" | "conversation_cluster";
                    "hello-v2-token-key"?: string;
                };
                experiments: {
                    /** Format: int64 */
                    enabled: number;
                };
                permissions: {
                    /** Format: int64 */
                    "max-default": number;
                    /** Format: int64 */
                    "max-custom": number;
                    /** Format: int64 */
                    default: number;
                };
            };
            "config-local": {
                [key: string]: string[];
            };
            version: string;
        };
        OCSMeta: {
            status: string;
            statuscode: number;
            message?: string;
            totalitems?: string;
            itemsperpage?: string;
        };
        PublicCapabilities: {
            spreed?: components["schemas"]["Capabilities"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "recording-backend": {
        parameters: {
            query?: never;
            header: {
                /** @description Random seed (at least 32 bytes) used together with the request body to generate the SHA256-HMAC request checksum */
                "talk-recording-random"?: string;
                /** @description SHA256-HMAC checksum over the concatenation of the random seed and the request body, signed with the shared recording secret, to verify authenticity from the recording backend */
                "talk-recording-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recording status updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Updating recording status is not possible */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                type: string;
                                error: {
                                    code: string;
                                    message: string;
                                };
                            };
                        };
                    };
                };
            };
            /** @description Missing permissions to update recording status */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                type: string;
                                error: {
                                    code: string;
                                    message: string;
                                };
                            };
                        };
                    };
                };
            };
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                type: string;
                                error: {
                                    code: string;
                                    message: string;
                                };
                            };
                        };
                    };
                };
            };
        };
    };
    "recording-store": {
        parameters: {
            query?: never;
            header: {
                /** @description Random seed (at least 32 bytes) used together with the room token to generate the SHA256-HMAC request checksum */
                "talk-recording-random"?: string;
                /** @description SHA256-HMAC checksum over the concatenation of the random seed and the room token, signed with the shared recording secret, to verify authenticity from the recording backend */
                "talk-recording-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description User that will own the recording file. `null` is actually not allowed and will always result in a "400 Bad Request". It's only allowed code-wise to handle requests where the post data exceeded the limits, so we can return a proper error instead of "500 Internal Server Error". */
                    owner?: string | null;
                    /**
                     * @description File name of the recording uploaded through a previously requested upload share. When provided, no multipart `file` is expected.
                     * @default null
                     */
                    fileName?: string | null;
                };
            };
        };
        responses: {
            /** @description Recording stored successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Storing recording is not possible */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                            };
                        };
                    };
                };
            };
            /** @description Missing permissions to store recording */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                type: string;
                                error: {
                                    code: string;
                                    message: string;
                                };
                            };
                        };
                    };
                };
            };
        };
    };
    "recording-request-upload": {
        parameters: {
            query?: never;
            header: {
                /** @description Random seed (at least 32 bytes) used together with the room token to generate the SHA256-HMAC request checksum */
                "talk-recording-random"?: string;
                /** @description SHA256-HMAC checksum over the concatenation of the random seed and the room token, signed with the shared recording secret, to verify authenticity from the recording backend */
                "talk-recording-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description User that will own the recording file. */
                    owner: string;
                    /** @description Suggested file name of the recording. The extension must be one of the allowed recording formats. */
                    fileName: string;
                };
            };
        };
        responses: {
            /** @description Upload share created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                token: string;
                                password: string;
                                fileName: string;
                            };
                        };
                    };
                };
            };
            /** @description Creating the upload share is not possible */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                            };
                        };
                    };
                };
            };
            /** @description Missing permissions to request the upload share */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                type: string;
                                error: {
                                    code: string;
                                    message: string;
                                };
                            };
                        };
                    };
                };
            };
        };
    };
}
