/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/bot/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List admin bots
         * @description This endpoint requires admin access
         */
        get: operations["bot-admin-list-bots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/certificate/expiration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the certificate expiration for a host
         * @description This endpoint requires admin access
         */
        get: operations["certificate-get-certificate-expiration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/hostedsignalingserver/requesttrial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a trial account
         * @description This endpoint requires admin access
         */
        post: operations["hosted_signaling_server-request-trial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/hostedsignalingserver/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete the account
         * @description This endpoint requires admin access
         */
        delete: operations["hosted_signaling_server-delete-account"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/bridge/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Matterbridge version
         * @description This endpoint requires admin access
         */
        get: operations["matterbridge_settings-get-matterbridge-version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/bridge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Stop all bridges
         * @description This endpoint requires admin access
         */
        delete: operations["matterbridge_settings-stop-all-bridges"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/recording/welcome/{serverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the welcome message of a recording server
         * @description This endpoint requires admin access
         */
        get: operations["recording-get-welcome-message"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/settings/sip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update SIP bridge settings
         * @description This endpoint requires admin access
         */
        post: operations["settings-setsip-settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/signaling/welcome/{serverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the welcome message from a signaling server
         * @description Only available for logged-in users because guests can not use the apps right now.
         *     This endpoint requires admin access
         */
        get: operations["signaling-get-welcome-message"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Bot: {
            /** @description A longer description of the bot helping moderators to decide if they want to enable this bot */
            description: string | null;
            /**
             * Format: int64
             * @description Unique numeric identifier of the bot on this server
             */
            id: number;
            /** @description Display name of the bot shown as author when it posts a message or reaction */
            name: string;
            /**
             * Format: int64
             * @description One of the [Bot states](https://nextcloud-talk.readthedocs.io/en/latest/constants#bot-states)
             */
            state: number;
        };
        BotWithDetails: components["schemas"]["Bot"] & {
            /**
             * Format: int64
             * @description Number of consecutive errors
             */
            error_count: number;
            /**
             * Format: int64
             * @description Feature flags for the bot (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#bot-features))
             */
            features: number;
            /**
             * Format: int64
             * @description UNIX timestamp of the last error
             */
            last_error_date: number;
            /** @description The last exception message or error response information when trying to reach the bot */
            last_error_message: string;
            /** @description URL endpoint that is triggered by this bot */
            url: string;
            /** @description Hash of the URL prefixed with `bot-` serves as `actorId` */
            url_hash: string;
        };
        Capabilities: {
            /** @description List of features available on the server */
            features: string[];
            /** @description List of features only available locally (not for federated conversations) */
            "features-local": string[];
            config: {
                attachments: {
                    /** @description Whether file sharing is allowed in conversations */
                    allowed: boolean;
                    /** @description User's attachment folder (only available for logged in users) */
                    folder?: string;
                };
                call: {
                    /** @description Whether calls are enabled */
                    enabled: boolean;
                    /** @description Whether breakout rooms are enabled */
                    "breakout-rooms": boolean;
                    /** @description Whether call recording is enabled */
                    recording: boolean;
                    /**
                     * Format: int64
                     * @description Whether recording consent is required (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#recording-consent-required))
                     */
                    "recording-consent": number;
                    /** @description List of supported reaction emojis during calls */
                    "supported-reactions": string[];
                    /** @description List of file names relative to the spreed/img/backgrounds/ web path, e.g. `2_home.jpg` */
                    "predefined-backgrounds": string[];
                    /** @description List of file paths relative to the server web root with leading slash, e.g. `/apps/spreed/img/backgrounds/2_home.jpg` */
                    "predefined-backgrounds-v2": string[];
                    /** @description Whether the user can upload custom virtual backgrounds */
                    "can-upload-background": boolean;
                    /** @description Whether SIP is enabled on the server */
                    "sip-enabled": boolean;
                    /** @description Whether SIP dial-out is enabled on the server */
                    "sip-dialout-enabled": boolean;
                    /** @description Default phone region of the server */
                    "default-phone-region": string;
                    /** @description Whether the user can enable SIP for conversations */
                    "can-enable-sip": boolean;
                    /** @description Whether calls start without media by default */
                    "start-without-media": boolean;
                    /**
                     * Format: int64
                     * @description Maximum duration of a call in seconds, `0` means unlimited
                     */
                    "max-duration": number;
                    /** @description Whether the blur virtual background is available */
                    "blur-virtual-background": boolean;
                    /** @description Whether end-to-end encryption is available */
                    "end-to-end-encryption": boolean;
                    /** @description Whether live transcription is available */
                    "live-transcription": boolean;
                    /** @description Whether live translation is available */
                    "live-translation": boolean;
                    /** @description The default target language for live transcription */
                    "live-transcription-target-language-id": string;
                    /** @description Whether to play sounds for call events */
                    "play-sounds": boolean;
                    /**
                     * Format: int64
                     * @description Maximum number of participants shown in the grid view
                     */
                    "grid-limit": number;
                    /** @description Whether the grid limit is enforced by the server */
                    "grid-limit-enforced": boolean;
                };
                chat: {
                    /**
                     * Format: int64
                     * @description Maximum length of a chat message
                     */
                    "max-length": number;
                    /**
                     * Format: int64
                     * @description Read privacy setting for the user (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#participant-read-status-privacy))
                     */
                    "read-privacy": number;
                    /** @description Whether translation providers are available */
                    "has-translation-providers": boolean;
                    /** @description Whether translation task providers are available */
                    "has-translation-task-providers": boolean;
                    /**
                     * Format: int64
                     * @description Typing privacy setting for the user (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#participant-typing-privacy))
                     */
                    "typing-privacy": number;
                    /**
                     * Format: int64
                     * @description Minimum number of chat messages before a summary can be generated
                     */
                    "summary-threshold": number;
                    /**
                     * @description Chat message rendering style (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#chat-style))
                     * @enum {string}
                     */
                    style: "split" | "unified";
                    /** @description Whether Matterbridge is enabled */
                    "matterbridge-enabled": boolean;
                };
                conversations: {
                    /** @description Whether the user can create conversations */
                    "can-create": boolean;
                    /** @description Whether passwords are enforced for public conversations */
                    "force-passwords": boolean;
                    /**
                     * @description Conversation list style (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#conversation-list-style))
                     * @enum {string}
                     */
                    "list-style": "two-lines" | "compact";
                    /**
                     * Format: int64
                     * @description Maximum length of a conversation description
                     */
                    "description-length": number;
                    /**
                     * Format: int64
                     * @description Retention period for event conversations in seconds, `0` means no retention
                     */
                    "retention-event": number;
                    /**
                     * Format: int64
                     * @description Retention period for phone conversations in seconds, `0` means no retention
                     */
                    "retention-phone": number;
                    /**
                     * Format: int64
                     * @description Retention period for instant meetings in seconds, `0` means no retention
                     */
                    "retention-instant-meetings": number;
                };
                federation: {
                    /** @description Whether federation is enabled */
                    enabled: boolean;
                    /** @description Whether incoming federation is enabled */
                    "incoming-enabled": boolean;
                    /** @description Whether outgoing federation is enabled */
                    "outgoing-enabled": boolean;
                    /** @description Whether only trusted servers are allowed for federation */
                    "only-trusted-servers": boolean;
                };
                previews: {
                    /**
                     * Format: int64
                     * @description Maximum GIF file size in bytes for previews
                     */
                    "max-gif-size": number;
                };
                signaling: {
                    /**
                     * Format: int64
                     * @description Maximum number of sessions that can be pinged in a single request
                     */
                    "session-ping-limit": number;
                    /**
                     * @description Signaling mode (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#signaling-modes))
                     * @enum {string}
                     */
                    mode: "internal" | "external" | "conversation_cluster";
                    /** @description Public key for hello v2 authentication */
                    "hello-v2-token-key"?: string;
                };
                experiments: {
                    /**
                     * Format: int64
                     * @description Bit-flag of enabled experiments
                     */
                    enabled: number;
                };
                "feature-hints": {
                    /** Format: int64 */
                    current: number;
                    /** Format: int64 */
                    hidden: number;
                };
                permissions: {
                    /**
                     * Format: int64
                     * @description Maximum default permissions (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
                     */
                    "max-default": number;
                    /**
                     * Format: int64
                     * @description Maximum custom permissions (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
                     */
                    "max-custom": number;
                    /**
                     * Format: int64
                     * @description Server default permissions (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
                     */
                    default: number;
                };
            };
            /** @description Map of config keys that are only available locally (not for federated conversations) */
            "config-local": {
                [key: string]: string[];
            };
            /** @description Version of the Talk app */
            version: string;
        };
        OCSMeta: {
            status: string;
            statuscode: number;
            message?: string;
            totalitems?: string;
            itemsperpage?: string;
        };
        PublicCapabilities: {
            spreed?: components["schemas"]["Capabilities"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "bot-admin-list-bots": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bot list returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["BotWithDetails"][];
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "certificate-get-certificate-expiration": {
        parameters: {
            query: {
                /** @description Host to check */
                host: string;
            };
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Certificate expiration returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                /** Format: int64 */
                                expiration_in_days: number | null;
                            };
                        };
                    };
                };
            };
            /** @description Getting certificate expiration is not possible */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "hosted_signaling_server-request-trial": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Server URL */
                    url: string;
                    /** @description Display name of the user */
                    name: string;
                    /** @description Email of the user */
                    email: string;
                    /** @description Language of the user */
                    language: string;
                    /** @description Country of the user */
                    country: string;
                };
            };
        };
        responses: {
            /** @description Trial requested successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                [key: string]: Record<string, never>;
                            };
                        };
                    };
                };
            };
            /** @description Requesting trial is not possible */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "hosted_signaling_server-delete-account": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Deleting account is not possible */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "matterbridge_settings-get-matterbridge-version": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bridge version returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                version: string;
                            };
                        };
                    };
                };
            };
            /** @description Getting bridge version is not possible */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                            };
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "matterbridge_settings-stop-all-bridges": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All bridges stopped successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: boolean;
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Stopping all bridges is not possible */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "recording-get-welcome-message": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description ID of the server */
                serverId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Welcome message returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                /** Format: double */
                                version: number;
                            };
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Recording server not found or not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "settings-setsip-settings": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description New SIP groups
                     * @default []
                     */
                    sipGroups?: string[];
                    /**
                     * @description New dial info
                     * @default
                     */
                    dialInInfo?: string;
                    /**
                     * @description New shared secret
                     * @default
                     */
                    sharedSecret?: string;
                };
            };
        };
        responses: {
            /** @description Successfully set new SIP settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "signaling-get-welcome-message": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v3";
                /** @description ID of the signaling server */
                serverId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Welcome message returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                version: string;
                                warning?: string;
                                features?: string[];
                            };
                        };
                    };
                };
            };
            /** @description Current user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Logged in account must be an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Signaling server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                version?: string;
                            };
                        };
                    };
                };
            };
        };
    };
}
