/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/room/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a room */
        get: operations["room-get-single-room"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/room/{token}/pin/{pin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify a dial-in PIN (SIP bridge) */
        get: operations["room-verify-dial-in-pin-deprecated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/room/{token}/verify-dialin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a dial-in PIN (SIP bridge) */
        post: operations["room-verify-dial-in-pin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/room/direct-dial-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Direct dial-in (SIP bridge)
         * @description Required capability: `sip-direct-dialin`
         */
        post: operations["room-direct-dial-in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/room/{token}/verify-dialout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a dial-out number (SIP bridge) */
        post: operations["room-verify-dial-out-number"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/room/{token}/open-dial-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a guest by their dial-in */
        post: operations["room-create-guest-by-dial-in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/spreed/api/{apiVersion}/room/{token}/rejected-dialout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Reset call ID of a dial-out participant when the SIP gateway rejected it */
        delete: operations["room-rejected-dial-out-request"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        BaseMessage: {
            /** @description Display name of the message author (can be empty for type `deleted_users` and `guests`) */
            actorDisplayName: string;
            /** @description Actor id of the message author */
            actorId: string;
            /** @description See [Constants - Actor types of chat messages](https://nextcloud-talk.readthedocs.io/en/latest/constants#actor-types-of-chat-messages) */
            actorType: string;
            /**
             * Format: int64
             * @description Unix time stamp when the message expires and should be removed from the clients UI without further note or warning (only available with `message-expiration` capability)
             */
            expirationTimestamp: number;
            /** @description Message string with placeholders (see [Rich Object String](https://github.com/nextcloud/server/issues/1706)) */
            message: string;
            /** @description Message parameters for `message` (see [Rich Object String](https://github.com/nextcloud/server/issues/1706)) */
            messageParameters: {
                [key: string]: components["schemas"]["RichObjectParameter"];
            };
            /** @description Currently known types are `comment`, `comment_deleted`, `system` and `command` */
            messageType: string;
            /** @description Empty for normal chat message or the type of the system message (untranslated) */
            systemMessage: string;
        };
        Capabilities: {
            /** @description List of features available on the server */
            features: string[];
            /** @description List of features only available locally (not for federated conversations) */
            "features-local": string[];
            config: {
                attachments: {
                    /** @description Whether file sharing is allowed in conversations */
                    allowed: boolean;
                    /** @description User's attachment folder (only available for logged in users) */
                    folder?: string;
                };
                call: {
                    /** @description Whether calls are enabled */
                    enabled: boolean;
                    /** @description Whether breakout rooms are enabled */
                    "breakout-rooms": boolean;
                    /** @description Whether call recording is enabled */
                    recording: boolean;
                    /**
                     * Format: int64
                     * @description Whether recording consent is required (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#recording-consent-required))
                     */
                    "recording-consent": number;
                    /** @description List of supported reaction emojis during calls */
                    "supported-reactions": string[];
                    /** @description List of file names relative to the spreed/img/backgrounds/ web path, e.g. `2_home.jpg` */
                    "predefined-backgrounds": string[];
                    /** @description List of file paths relative to the server web root with leading slash, e.g. `/apps/spreed/img/backgrounds/2_home.jpg` */
                    "predefined-backgrounds-v2": string[];
                    /** @description Whether the user can upload custom virtual backgrounds */
                    "can-upload-background": boolean;
                    /** @description Whether SIP is enabled on the server */
                    "sip-enabled": boolean;
                    /** @description Whether SIP dial-out is enabled on the server */
                    "sip-dialout-enabled": boolean;
                    /** @description Default phone region of the server */
                    "default-phone-region": string;
                    /** @description Whether the user can enable SIP for conversations */
                    "can-enable-sip": boolean;
                    /** @description Whether calls start without media by default */
                    "start-without-media": boolean;
                    /**
                     * Format: int64
                     * @description Maximum duration of a call in seconds, `0` means unlimited
                     */
                    "max-duration": number;
                    /** @description Whether the blur virtual background is available */
                    "blur-virtual-background": boolean;
                    /** @description Whether end-to-end encryption is available */
                    "end-to-end-encryption": boolean;
                    /** @description Whether live transcription is available */
                    "live-transcription": boolean;
                    /** @description Whether live translation is available */
                    "live-translation": boolean;
                    /** @description The default target language for live transcription */
                    "live-transcription-target-language-id": string;
                    /** @description Whether to play sounds for call events */
                    "play-sounds": boolean;
                    /**
                     * Format: int64
                     * @description Maximum number of participants shown in the grid view
                     */
                    "grid-limit": number;
                    /** @description Whether the grid limit is enforced by the server */
                    "grid-limit-enforced": boolean;
                };
                chat: {
                    /**
                     * Format: int64
                     * @description Maximum length of a chat message
                     */
                    "max-length": number;
                    /**
                     * Format: int64
                     * @description Read privacy setting for the user (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#participant-read-status-privacy))
                     */
                    "read-privacy": number;
                    /** @description Whether translation providers are available */
                    "has-translation-providers": boolean;
                    /** @description Whether translation task providers are available */
                    "has-translation-task-providers": boolean;
                    /**
                     * Format: int64
                     * @description Typing privacy setting for the user (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#participant-typing-privacy))
                     */
                    "typing-privacy": number;
                    /**
                     * Format: int64
                     * @description Minimum number of chat messages before a summary can be generated
                     */
                    "summary-threshold": number;
                    /**
                     * @description Chat message rendering style (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#chat-style))
                     * @enum {string}
                     */
                    style: "split" | "unified";
                    /** @description Whether Matterbridge is enabled */
                    "matterbridge-enabled": boolean;
                };
                conversations: {
                    /** @description Whether the user can create conversations */
                    "can-create": boolean;
                    /** @description Whether passwords are enforced for public conversations */
                    "force-passwords": boolean;
                    /**
                     * @description Conversation list style (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#conversation-list-style))
                     * @enum {string}
                     */
                    "list-style": "two-lines" | "compact";
                    /**
                     * Format: int64
                     * @description Maximum length of a conversation description
                     */
                    "description-length": number;
                    /**
                     * Format: int64
                     * @description Retention period for event conversations in seconds, `0` means no retention
                     */
                    "retention-event": number;
                    /**
                     * Format: int64
                     * @description Retention period for phone conversations in seconds, `0` means no retention
                     */
                    "retention-phone": number;
                    /**
                     * Format: int64
                     * @description Retention period for instant meetings in seconds, `0` means no retention
                     */
                    "retention-instant-meetings": number;
                };
                federation: {
                    /** @description Whether federation is enabled */
                    enabled: boolean;
                    /** @description Whether incoming federation is enabled */
                    "incoming-enabled": boolean;
                    /** @description Whether outgoing federation is enabled */
                    "outgoing-enabled": boolean;
                    /** @description Whether only trusted servers are allowed for federation */
                    "only-trusted-servers": boolean;
                };
                previews: {
                    /**
                     * Format: int64
                     * @description Maximum GIF file size in bytes for previews
                     */
                    "max-gif-size": number;
                };
                signaling: {
                    /**
                     * Format: int64
                     * @description Maximum number of sessions that can be pinged in a single request
                     */
                    "session-ping-limit": number;
                    /**
                     * @description Signaling mode (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#signaling-modes))
                     * @enum {string}
                     */
                    mode: "internal" | "external" | "conversation_cluster";
                    /** @description Public key for hello v2 authentication */
                    "hello-v2-token-key"?: string;
                };
                experiments: {
                    /**
                     * Format: int64
                     * @description Bit-flag of enabled experiments
                     */
                    enabled: number;
                };
                "feature-hints": {
                    /** Format: int64 */
                    current: number;
                    /** Format: int64 */
                    hidden: number;
                };
                permissions: {
                    /**
                     * Format: int64
                     * @description Maximum default permissions (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
                     */
                    "max-default": number;
                    /**
                     * Format: int64
                     * @description Maximum custom permissions (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
                     */
                    "max-custom": number;
                    /**
                     * Format: int64
                     * @description Server default permissions (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
                     */
                    default: number;
                };
            };
            /** @description Map of config keys that are only available locally (not for federated conversations) */
            "config-local": {
                [key: string]: string[];
            };
            /** @description Version of the Talk app */
            version: string;
        };
        ChatMessage: components["schemas"]["BaseMessage"] & {
            /**
             * @description Set to `true` when the message was deleted
             * @enum {boolean}
             */
            deleted?: true;
            /**
             * Format: int64
             * @description ID of the comment
             */
            id: number;
            /** @description True if the user can post a reply to this message (only available with `chat-replies` capability) */
            isReplyable: boolean;
            /** @description Whether the message should be rendered as markdown or shown as plain text */
            markdown: boolean;
            /** @description An array map with relation between reaction emoji and total count of reactions with this emoji */
            reactions: {
                [key: string]: number;
            };
            /** @description When the user reacted this is the list of emojis the user reacted with */
            reactionsSelf?: string[];
            /** @description A reference string that was given while posting the message to be able to identify a sent message again (only available with `chat-reference-id` capability) */
            referenceId: string;
            /**
             * Format: int64
             * @description Timestamp in seconds and UTC time zone
             */
            timestamp: number;
            /** @description Conversation token */
            token: string;
            /** @description Display name of the last editing author (only available with `edit-messages` capability and when the message was actually edited) */
            lastEditActorDisplayName?: string;
            /** @description Actor id of the last editing author (only available with `edit-messages` capability and when the message was actually edited) */
            lastEditActorId?: string;
            /** @description Actor type of the last editing author - See [Constants - Actor types of chat messages](https://nextcloud-talk.readthedocs.io/en/latest/constants#actor-types-of-chat-messages) (only available with `edit-messages` capability and when the message was actually edited) */
            lastEditActorType?: string;
            /**
             * Format: int64
             * @description Unix time stamp when the message was last edited (only available with `edit-messages` capability and when the message was actually edited)
             */
            lastEditTimestamp?: number;
            /** @description Whether the message was sent silently (only available with `silent-send-state` capability) */
            silent?: boolean;
            /**
             * Format: int64
             * @description Thread ID if this message is part of a thread
             */
            threadId?: number;
            /** @description Whether this message is the root of a thread */
            isThread?: boolean;
            /** @description Title of the thread if this message is the root of a thread */
            threadTitle?: string;
            /**
             * Format: int64
             * @description Number of replies in the thread if this message is the root of a thread
             */
            threadReplies?: number;
            /** @description Additional metadata of the message */
            metaData?: components["schemas"]["ChatMessageMetaData"];
        };
        ChatMessageMetaData: {
            /** @description Actor type of the attendee that pinned the message - Required capability: `pinned-messages` */
            pinnedActorType?: string;
            /** @description Actor ID of the attendee that pinned the message - Required capability: `pinned-messages` */
            pinnedActorId?: string;
            /** @description Display name of the attendee that pinned the message - Required capability: `pinned-messages` */
            pinnedActorDisplayName?: string;
            /**
             * Format: int64
             * @description Timestamp when the message was pinned - Required capability: `pinned-messages`
             */
            pinnedAt?: number;
            /**
             * Format: int64
             * @description Timestamp until when the message is pinned. If missing the message is pinned infinitely - Required capability: `pinned-messages`
             */
            pinnedUntil?: number;
            /**
             * Format: int64
             * @description Set when a thread is created with this message. If missing, no thread creation is associated with this message
             */
            threadId?: number;
            /** @description Set when a thread is created with this message. If missing, no thread creation is associated with this message */
            threadTitle?: string;
        };
        ChatProxyMessage: components["schemas"]["BaseMessage"];
        OCSMeta: {
            status: string;
            statuscode: number;
            message?: string;
            totalitems?: string;
            itemsperpage?: string;
        };
        PublicCapabilities: {
            spreed?: components["schemas"]["Capabilities"];
        };
        RichObjectParameter: {
            /** @description Object type (see [Rich Object String](https://github.com/nextcloud/server/issues/1706)) */
            type: string;
            /** @description Object id */
            id: string;
            /** @description Visible name */
            name: string;
            /** @description Server URL for federated users */
            server?: string;
            /** @description URL of the object */
            link?: string;
            /**
             * @description Type of the call
             * @enum {string}
             */
            "call-type"?: "one2one" | "group" | "public";
            /** @description URL of the icon */
            "icon-url"?: string;
            /** @description ID of a message that this object refers to */
            "message-id"?: string;
            /** @description Name of the Deck board */
            boardname?: string;
            /** @description Name of the Deck stack */
            stackname?: string;
            /** @description File size in bytes */
            size?: string;
            /** @description Path of the file */
            path?: string;
            /** @description Mimetype of the file */
            mimetype?: string;
            /**
             * @description Whether a preview is available for the file
             * @enum {string}
             */
            "preview-available"?: "yes" | "no";
            /**
             * @description Whether the download should be hidden for the file
             * @enum {string}
             */
            "hide-download"?: "yes" | "no";
            /** @description Modification time of the file as UNIX timestamp */
            mtime?: string;
            /** @description Latitude of a location */
            latitude?: string;
            /** @description Longitude of a location */
            longitude?: string;
            /** @description Description of the object */
            description?: string;
            /** @description URL of a thumbnail */
            thumb?: string;
            /** @description Website URL */
            website?: string;
            /**
             * @description Visibility of the object
             * @enum {string}
             */
            visibility?: "0" | "1";
            /**
             * @description Whether the object is assignable
             * @enum {string}
             */
            assignable?: "0" | "1";
            /** @description Conversation token */
            conversation?: string;
            /** @description ETag of the object for caching */
            etag?: string;
            /** @description Permissions for the file */
            permissions?: string;
            /** @description Width of the object (e.g. image, video) */
            width?: string;
            /** @description Height of the object (e.g. image, video) */
            height?: string;
            /** @description Blurhash of the image */
            blurhash?: string;
        };
        Room: {
            /** @description The unique identifier for the given actor type */
            actorId: string;
            /** @description The cloud id of the invited user */
            invitedActorId?: string;
            /** @description Actor type of the current user (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-types)) */
            actorType: string;
            /**
             * Format: int64
             * @description Unique attendee id
             */
            attendeeId: number;
            /**
             * Format: int64
             * @description Dedicated permissions for the current participant, if not `Custom` this are not the resulting permissions (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
             */
            attendeePermissions: number;
            /** @description Unique dial-in authentication code for this user, when the conversation has SIP enabled (see `sipEnabled` attribute) */
            attendeePin: string | null;
            /** @description Version of conversation avatar used to easier expiration of the avatar in case a moderator updates it, since the avatar endpoint should be cached for 24 hours. (only available with `avatar` capability) */
            avatarVersion: string;
            /**
             * Format: int64
             * @description Breakout room configuration mode (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#breakout-room-modes)) (only available with `breakout-rooms-v1` capability)
             */
            breakoutRoomMode: number;
            /**
             * Format: int64
             * @description Breakout room status (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#breakout-room-status)) (only available with `breakout-rooms-v1` capability)
             */
            breakoutRoomStatus: number;
            /**
             * Format: int64
             * @description Combined flag of all participants in the current call (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#participant-in-call-flag), only available with `conversation-call-flags` capability)
             */
            callFlag: number;
            /**
             * Format: int64
             * @description Call permissions, if not `Custom` this are not the resulting permissions, if set they will reset after the end of the call (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
             */
            callPermissions: number;
            /**
             * Format: int64
             * @description Type of call recording (see [Constants - Call recording status](https://nextcloud-talk.readthedocs.io/en/latest/constants#call-recording-status)) (only available with `recording-v1` capability)
             * @enum {integer}
             */
            callRecording: 0 | 1 | 2 | 3 | 4 | 5;
            /**
             * Format: int64
             * @description Timestamp when the call was started (only available with `recording-v1` capability)
             */
            callStartTime: number;
            /** @description Flag if the user can delete the conversation for everyone (not possible without moderator permissions or in one-to-one conversations) */
            canDeleteConversation: boolean;
            /** @description Whether the given user can enable SIP for this conversation. Note that when the token is not-numeric only, SIP can not be enabled even if the user is permitted and a moderator of the conversation */
            canEnableSIP: boolean;
            /** @description Flag if the user can leave the conversation (not possible for the last user with moderator permissions) */
            canLeaveConversation: boolean;
            /** @description Flag if the user can start a new call in this conversation (joining is always possible) (only available with `start-call-flag` capability) */
            canStartCall: boolean;
            /**
             * Format: int64
             * @description Default permissions for new participants (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
             */
            defaultPermissions: number;
            /** @description Description of the conversation (can also be empty) (only available with `room-description` capability) */
            description: string;
            /** @description `name` if non-empty, otherwise it falls back to a list of participants */
            displayName: string;
            /** @description Flag if the conversation has an active call */
            hasCall: boolean;
            /** @description Flag if the conversation has a password */
            hasPassword: boolean;
            /**
             * Format: int64
             * @description Identifier of the conversation
             */
            id: number;
            /** @description Flag if the conversation has a custom avatar (only available with `avatar` capability) */
            isCustomAvatar: boolean;
            /** @description Flag if the conversation is favorited by the user */
            isFavorite: boolean;
            /**
             * Format: int64
             * @description Timestamp of the last activity in the conversation, in seconds and UTC time zone
             */
            lastActivity: number;
            /**
             * Format: int64
             * @description ID of the last message read by every user that has read privacy set to public in a room. When the user themself has it set to private the value is `0` (only available with `chat-read-status` capability)
             */
            lastCommonReadMessage: number;
            /** @description Last message in a conversation if available, otherwise empty. **Note:** Even when given the message will not contain the `parent` or `reactionsSelf` attribute due to performance reasons */
            lastMessage?: components["schemas"]["RoomLastMessage"];
            /**
             * Format: int64
             * @description Timestamp of the user's session making the request
             */
            lastPing: number;
            /**
             * Format: int64
             * @description ID of the last read message in a room (only available with `chat-read-marker` capability)
             */
            lastReadMessage: number;
            /**
             * Format: int64
             * @description Listable scope for the room (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#listable-scope)) (only available with `listable-rooms` capability)
             */
            listable: number;
            /** @description ID of the language to use for live transcriptions in the room, */
            liveTranscriptionLanguageId: string;
            /**
             * Format: int64
             * @description Webinar lobby restriction (0-1), if the participant is a moderator they can always join the conversation (only available with `webinary-lobby` capability) (See [Webinar lobby states](https://nextcloud-talk.readthedocs.io/en/latest/constants#webinar-lobby-states))
             */
            lobbyState: number;
            /**
             * Format: int64
             * @description Timestamp when the lobby will be automatically disabled (only available with `webinary-lobby` capability)
             */
            lobbyTimer: number;
            /**
             * Format: int64
             * @description Whether all participants can mention using `@all` or only moderators (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#mention-permissions)) (only available with `mention-permissions` capability)
             * @enum {integer}
             */
            mentionPermissions: 0 | 1;
            /**
             * Format: int64
             * @description The message expiration time in seconds in this chat. Zero if disabled. (only available with `message-expiration` capability)
             */
            messageExpiration: number;
            /** @description Name of the conversation (can also be empty) */
            name: string;
            /**
             * Format: int64
             * @description The call notification level for the user (see [Participant call notification levels](https://nextcloud-talk.readthedocs.io/en/latest/constants#participant-call-notification-levels))
             */
            notificationCalls: number;
            /**
             * Format: int64
             * @description The notification level for the user (See [Participant notification levels](https://nextcloud-talk.readthedocs.io/en/latest/constants#participant-notification-levels))
             */
            notificationLevel: number;
            /** @description See [Object types](https://nextcloud-talk.readthedocs.io/en/latest/constants#object-types) documentation for explanation */
            objectId: string;
            /** @description The type of object that the conversation is associated with (See [Object types](https://nextcloud-talk.readthedocs.io/en/latest/constants#object-types)) */
            objectType: string;
            /**
             * Format: int64
             * @description "In call" flags of the user's session making the request (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#participant-in-call-flag)) (only available with `in-call-flags` capability)
             */
            participantFlags: number;
            /**
             * Format: int64
             * @description Permissions level of the current user (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#participant-types))
             */
            participantType: number;
            /**
             * Format: int64
             * @description Combined final permissions for the current participant, permissions are picked in order of attendee then call then default and the first which is `Custom` will apply (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#attendee-permissions))
             */
            permissions: number;
            /**
             * Format: int64
             * @description Read-only state for the current user (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#read-only-states)) (only available with `read-only-rooms` capability)
             */
            readOnly: number;
            /**
             * Format: int64
             * @description Whether recording consent is required before joining a call (Only 0 and 1 will be returned, see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#recording-consent-required)) (only available with `recording-consent` capability)
             */
            recordingConsent: number;
            remoteServer?: string;
            remoteToken?: string;
            /** @description `'0'` if not connected, otherwise an up to 512 character long string that is the identifier of the user's session making the request. Should only be used to pre-check if the user joined already with this session, but this might be outdated by the time of usage, so better check via [Get list of participants in a conversation](https://nextcloud-talk.readthedocs.io/en/latest/participant/#get-list-of-participants-in-a-conversation) */
            sessionId: string;
            /**
             * Format: int64
             * @description SIP enable status (see [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants#sip-states))
             */
            sipEnabled: number;
            /** @description Only available for one-to-one conversations, when `includeStatus=true` is set and the user has a status */
            status?: string;
            /**
             * Format: int64
             * @description Only available for one-to-one conversations, when `includeStatus=true` is set and the user has a status, can still be null even with a status
             */
            statusClearAt?: number | null;
            /** @description Only available for one-to-one conversations, when `includeStatus=true` is set and the user has a status, can still be null even with a status */
            statusIcon?: string | null;
            /** @description Only available for one-to-one conversations, when `includeStatus=true` is set and the user has a status, can still be null even with a status */
            statusMessage?: string | null;
            /** @description Token identifier of the conversation which is used for further interaction */
            token: string;
            /**
             * Format: int64
             * @description See list of conversation types in the [constants list](https://nextcloud-talk.readthedocs.io/en/latest/constants/#conversation-types)
             */
            type: number;
            /** @description Flag if the user was mentioned since their last visit */
            unreadMention: boolean;
            /** @description Flag if the user was mentioned directly (ignoring `@all` mentions) since their last visit (only available with `direct-mention-flag` capability) */
            unreadMentionDirect: boolean;
            /**
             * Format: int64
             * @description Number of unread chat messages in the conversation (only available with `chat-v2` capability)
             */
            unreadMessages: number;
            /** @description Flag if the conversation is archived by the user (only available with `archived-conversations-v2` capability) */
            isArchived: boolean;
            /** @description Required capability: `important-conversations` */
            isImportant: boolean;
            /** @description Required capability: `sensitive-conversations` */
            isSensitive: boolean;
            /**
             * Format: int64
             * @description Required capability: `pinned-messages`
             */
            lastPinnedId: number;
            /**
             * Format: int64
             * @description Required capability: `pinned-messages`
             */
            hiddenPinnedId: number;
            /**
             * Format: int64
             * @description Required capability: `scheduled-messages` (local)
             */
            hasScheduledMessages: number;
            /**
             * Format: int64
             * @description Bit-flag of enabled attributes of this conversation (only available with capability: `conversation-attributes`). See [attributes list](https://nextcloud-talk.readthedocs.io/en/latest/constants/#conversation-attributes) for details
             */
            attributes: number;
        };
        RoomLastMessage: components["schemas"]["ChatMessage"] | components["schemas"]["ChatProxyMessage"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "room-get-single-room": {
        parameters: {
            query?: never;
            header: {
                /** @description Set to 1 when the request is performed by another Nextcloud Server to indicate a federation request */
                "x-nextcloud-federation"?: string;
                /** @description Random seed used to generate the request checksum */
                "talk-sipbridge-random"?: string;
                /** @description Checksum over the request body to verify authenticity from the Sipbridge */
                "talk-sipbridge-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v4";
                /** @description Token of the room */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room returned */
            200: {
                headers: {
                    "X-Nextcloud-Talk-Hash"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Room"];
                        };
                    };
                };
            };
            /** @description SIP request invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "room-verify-dial-in-pin-deprecated": {
        parameters: {
            query?: never;
            header: {
                /** @description Random seed used to generate the request checksum */
                "talk-sipbridge-random"?: string;
                /** @description Checksum over the request body to verify authenticity from the Sipbridge */
                "talk-sipbridge-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v4";
                token: string;
                /** @description PIN the participant used to dial-in */
                pin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participant returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Room"];
                        };
                    };
                };
            };
            /** @description SIP request invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Participant not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description SIP dial-in is not configured */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "room-verify-dial-in-pin": {
        parameters: {
            query?: never;
            header: {
                /** @description Random seed used to generate the request checksum */
                "talk-sipbridge-random"?: string;
                /** @description Checksum over the request body to verify authenticity from the Sipbridge */
                "talk-sipbridge-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v4";
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description PIN the participant used to dial-in */
                    pin: string;
                };
            };
        };
        responses: {
            /** @description Participant returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Room"];
                        };
                    };
                };
            };
            /** @description SIP request invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Participant not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description SIP dial-in is not configured */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "room-direct-dial-in": {
        parameters: {
            query?: never;
            header: {
                /** @description Random seed used to generate the request checksum */
                "talk-sipbridge-random"?: string;
                /** @description Checksum over the request body to verify authenticity from the Sipbridge */
                "talk-sipbridge-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v4";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Phone number that is called */
                    phoneNumber: string;
                    /** @description Phone number of the person calling in */
                    caller: string;
                };
            };
        };
        responses: {
            /** @description Call conversation created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Room"];
                        };
                    };
                };
            };
            /** @description SIP request invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Number is not assigned to any user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Error occurred while creating conversation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description SIP dial-in is not configured */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "room-verify-dial-out-number": {
        parameters: {
            query?: never;
            header: {
                /** @description Random seed used to generate the request checksum */
                "talk-sipbridge-random"?: string;
                /** @description Checksum over the request body to verify authenticity from the Sipbridge */
                "talk-sipbridge-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v4";
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description E164 formatted phone number */
                    number: string;
                    /**
                     * @description Additional details to verify the validity of the request
                     * @default {}
                     */
                    options?: {
                        actorId?: string;
                        actorType?: string;
                        /** Format: int64 */
                        attendeeId?: number;
                    };
                };
            };
        };
        responses: {
            /** @description Participant created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Room"];
                        };
                    };
                };
            };
            /** @description Phone number and details could not be confirmed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description SIP request invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Phone number is not invited as a participant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description SIP dial-out is not configured */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "room-create-guest-by-dial-in": {
        parameters: {
            query?: never;
            header: {
                /** @description Random seed used to generate the request checksum */
                "talk-sipbridge-random"?: string;
                /** @description Checksum over the request body to verify authenticity from the Sipbridge */
                "talk-sipbridge-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v4";
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participant created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Room"];
                        };
                    };
                };
            };
            /** @description SIP not enabled */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description SIP request invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "room-rejected-dial-out-request": {
        parameters: {
            query: {
                /** @description The call ID provided by the SIP bridge earlier to uniquely identify the call to terminate */
                callId: string;
                /** @description Additional details to verify the validity of the request */
                options?: string;
            };
            header: {
                /** @description Random seed used to generate the request checksum */
                "talk-sipbridge-random"?: string;
                /** @description Checksum over the request body to verify authenticity from the Sipbridge */
                "talk-sipbridge-checksum"?: string;
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v4";
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Call ID reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Call ID mismatch or attendeeId not found in $options */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description SIP request invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Participant was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description SIP dial-out is not configured */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
}
