/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/ocs/v2.php/apps/dav/api/v1/direct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a direct link to a file */
        post: operations["direct-get-url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/dav/api/v1/events/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get information about upcoming events */
        get: operations["upcoming_events-get-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/dav/api/v1/outOfOffice/{userId}/now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently configured out-of-office data of a user */
        get: operations["out_of_office-get-current-out-of-office-data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/dav/api/v1/outOfOffice/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the configured out-of-office data of a user. */
        get: operations["out_of_office-get-out-of-office"];
        put?: never;
        /** Set out-of-office absence */
        post: operations["out_of_office-set-out-of-office"];
        /** Clear the out-of-office */
        delete: operations["out_of_office-clear-out-of-office"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Capabilities: {
            dav: {
                chunking: string;
                bulkupload?: string;
                "absence-supported"?: boolean;
                "absence-replacement"?: boolean;
            };
        };
        CurrentOutOfOfficeData: components["schemas"]["OutOfOfficeDataCommon"] & {
            id: string;
            /** Format: int64 */
            startDate: number;
            /** Format: int64 */
            endDate: number;
            shortMessage: string;
        };
        OCSMeta: {
            status: string;
            statuscode: number;
            message?: string;
            totalitems?: string;
            itemsperpage?: string;
        };
        OutOfOfficeData: components["schemas"]["OutOfOfficeDataCommon"] & {
            /** Format: int64 */
            id: number;
            firstDay: string;
            lastDay: string;
            status: string;
        };
        OutOfOfficeDataCommon: {
            userId: string;
            message: string;
            replacementUserId: string | null;
            replacementUserDisplayName: string | null;
        };
        UpcomingEvent: {
            uri: string;
            calendarUri: string;
            /** Format: int64 */
            start: number | null;
            summary: string | null;
            location: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "direct-get-url": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description ID of the file
                     */
                    fileId: number;
                    /**
                     * Format: int64
                     * @description Duration until the link expires
                     */
                    expirationTime: number;
                };
            };
        };
        responses: {
            /** @description Direct link returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                url: string;
                            };
                        };
                    };
                };
            };
            /** @description Getting direct link is not possible */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description Missing permissions to get direct link */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "upcoming_events-get-events": {
        parameters: {
            query?: {
                /** @description location/URL to filter by */
                location?: string | null;
            };
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upcoming events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                events: components["schemas"]["UpcomingEvent"][];
                            };
                        };
                    };
                };
            };
            /** @description When not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "out_of_office-get-current-out-of-office-data": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description The user id to get out-of-office data for. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Out-of-office data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["CurrentOutOfOfficeData"];
                        };
                    };
                };
            };
            /** @description No out-of-office data was found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "out_of_office-get-out-of-office": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description The user id to get out-of-office data for. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Out-of-office data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["OutOfOfficeData"];
                        };
                    };
                };
            };
            /** @description No out-of-office data was found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "out_of_office-set-out-of-office": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description First day of the absence in format `YYYY-MM-DD` */
                    firstDay: string;
                    /** @description Last day of the absence in format `YYYY-MM-DD` */
                    lastDay: string;
                    /** @description Short text that is set as user status during the absence */
                    status: string;
                    /** @description Longer multiline message that is shown to others during the absence */
                    message: string;
                    /** @description User id of the replacement user */
                    replacementUserId?: string | null;
                    /** @description Display name of the replacement user */
                    replacementUserDisplayName?: string | null;
                };
            };
        };
        responses: {
            /** @description Absence data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["OutOfOfficeData"];
                        };
                    };
                };
            };
            /** @description When the first day is not before the last day */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                /** @enum {string} */
                                error: "firstDay";
                            };
                        };
                    };
                };
            };
            /** @description When the user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description When the replacementUserId was provided but replacement user was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
    "out_of_office-clear-out-of-office": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description When the absence was cleared successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
            /** @description When the user is not logged in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: unknown;
                        };
                    };
                };
            };
        };
    };
}
