# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: debugging

on: pull_request

jobs:
  debugging:
    runs-on: ubuntu-latest

    steps:
      - name: Test ${{ github.ref }}
        continue-on-error: true
        run: echo '${{ github.ref }}'
      - name: Test ${{ github.ref_name }}
        continue-on-error: true
        run: echo '${{ github.ref_name }}'
      - name: Test contains('/nextcloud/vue-', github.ref)
        continue-on-error: true
        run: echo contains('/nextcloud/vue-', github.ref)
      - name: Test contains('/webrtc-adapter-', github.ref)
        continue-on-error: true
        run: echo contains('/webrtc-adapter-', github.ref)
      - name: Test contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), github.ref)
        continue-on-error: true
        run: echo contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), github.ref)

      - name: JS
        continue-on-error: true
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(github.ref)
            console.log(contains('/nextcloud/vue-', github.ref))
            console.log(contains('/webrtc-adapter-', github.ref))
            console.log(contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), github.ref))
