# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: debugging

on: pull_request

jobs:
  debugging:
    runs-on: ubuntu-latest

    steps:
      - uses: mdecoleman/pr-branch-name@2.0.0
        id: branchname
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), steps.branchname.outputs.branch) != true
        if: contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), steps.branchname.outputs.branch) != true
        run: echo 'contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), steps.branchname.outputs.branch) != true'

      - name: Test contains(fromJSON('["/webrtc-adapter-"]'), steps.branchname.outputs.branch) != true
        if: contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), steps.branchname.outputs.branch) != true
        run: echo 'contains(fromJSON('["/webrtc-adapter-"]'), steps.branchname.outputs.branch) != true'

      - name: Test contains(fromJSON('["/nextcloud/vue-"'), steps.branchname.outputs.branch) != true
        if: contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), steps.branchname.outputs.branch) != true
        run: echo 'contains(fromJSON('["/nextcloud/vue-"'), steps.branchname.outputs.branch) != true'

      - name: Test contains('/nextcloud/vue-', steps.branchname.outputs.branch) != true
        if: contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), steps.branchname.outputs.branch) != true
        run: echo 'contains('/nextcloud/vue-', steps.branchname.outputs.branch) != true'

      - run: echo ${{ steps.vars.outputs.branch }}
      - name: Test ${{ github.ref }}
        continue-on-error: true
        run: echo '${{ github.ref }}'
      - name: Test ${{ github.event.pull_request }}
        continue-on-error: true
        run: echo '${{ github.ref_name }}'
      - name: Test contains('/nextcloud/vue-', github.ref)
        continue-on-error: true
        run: echo contains('/nextcloud/vue-', github.ref)
      - name: Test contains('/webrtc-adapter-', github.ref)
        continue-on-error: true
        run: echo contains('/webrtc-adapter-', github.ref)
      - name: Test contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), github.ref)
        continue-on-error: true
        run: echo contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), github.ref)

      - name: JS
        continue-on-error: true
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(github.ref)
            console.log(contains('/nextcloud/vue-', github.ref))
            console.log(contains('/webrtc-adapter-', github.ref))
            console.log(contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), github.ref))
