# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Dependabot

on:
  pull_request_target:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

concurrency:
  group: dependabot-approve-merge-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  auto-approve-merge:
    runs-on: ubuntu-latest
    permissions:
      # for hmarr/auto-approve-action to approve PRs
      pull-requests: write

    steps:
      # GitHub actions bot approve
      - run: |
        echo '${{ github.ref }}'
        echo github.ref
        echo contains('/nextcloud/vue-', github.ref)
        echo contains('/webrtc-adapter-', github.ref)
        echo contains(fromJSON('["/nextcloud/vue-", "/webrtc-adapter-"]'), github.ref)
