# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

# TODO: Remove this after a grace period of 6 months to give everyone the chance to switch to the new workflow name
# TODO: To be removed end of 2026.
name: No-op please switch to npm-build.yml

on: pull_request

permissions:
  contents: none

concurrency:
  group: node-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  summary:
    runs-on: ubuntu-latest-low
    if: always()

    # This is the summary, we just avoid to rename it so that branch protection rules still match
    name: node

    steps:
      - name: No-op please switch to npm-build.yml
        run: echo "The workflow has been renamed, please switch to npm-build.yml from organization templates"; exit 1;
