# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Update nextcloud/ocp

on:
  workflow_dispatch:
  schedule:
    - cron: "5 2 * * 0"

permissions:
  contents: read
  issues: write

jobs:
  update-nextcloud-ocp:
    runs-on: ubuntu-latest

    # Only allowed to be run on nextcloud repositories
    if: ${{ github.repository_owner == 'nextcloud' }}

    strategy:
      fail-fast: false
      matrix:
        branches:
          - ${{ github.event.repository.default_branch }}
          - 'stable34'
          - 'stable33'
          - 'stable32'

    name: update-nextcloud-ocp-${{ matrix.branches }}

    steps:
      - id: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ matrix.branches }}
          submodules: true
        continue-on-error: true

      - name: Set up php8.3
        if: steps.checkout.outcome == 'success'
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.3
          # https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read codeowners
        if: steps.checkout.outcome == 'success'
        id: codeowners
        run: |
          grep '/appinfo/info.xml' .github/CODEOWNERS | cut -f 2- -d ' ' | xargs | awk '{ print "codeowners="$0 }' >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Install composer dependencies
        if: steps.checkout.outcome == 'success'
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Check composer bin for nextcloud/ocp exists
        id: check_composer_bin
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: vendor-bin/nextcloud-ocp/composer.json

      - name: Composer update nextcloud/ocp
        id: update_branch
        env:
          USE_COMPOSER_BIN: ${{ steps.check_composer_bin.outputs.files_exists }}
          BRANCH_NAME: ${{ matrix.branches }}
        run: |
          COMPOSER_CMD='composer'
          if [[ "$USE_COMPOSER_BIN" == 'true' ]]; then
            COMPOSER_CMD='composer bin nextcloud-ocp'
          fi

          PACKAGE_VERSION="nextcloud/ocp:dev-$BRANCH_NAME"
          if [[ "$BRANCH_NAME" == 'main' ]]; then
            PACKAGE_VERSION='nextcloud/ocp:dev-master'
          fi

          echo $COMPOSER_CMD require --dev $PACKAGE_VERSION
          $COMPOSER_CMD require --dev $PACKAGE_VERSION

      - name: Raise on issue on failure
        uses: dacbd/create-issue-action@cdb57ab6ff8862aa09fee2be6ba77a59581921c2 # v2.0.0
        if: ${{ steps.checkout.outcome == 'success' && failure() && steps.update_branch.conclusion == 'failure' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Failed to update nextcloud/ocp package on branch ${{ matrix.branches }}'
          body: 'Please check the output of the GitHub action and manually resolve the issues<br>${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}<br>${{ steps.codeowners.outputs.codeowners }}'

      - name: Create Pull Request
        if: steps.checkout.outcome == 'success'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          commit-message: 'chore(dev-deps): Bump nextcloud/ocp package'
          committer: GitHub <noreply@github.com>
          author: nextcloud-command <nextcloud-command@users.noreply.github.com>
          signoff: true
          branch: 'automated/noid/${{ matrix.branches }}-update-nextcloud-ocp'
          title: '[${{ matrix.branches }}] Update nextcloud/ocp dependency'
          add-path: |
            composer.json
            composer.lock
            vendor-bin/nextcloud-ocp/composer.json
            vendor-bin/nextcloud-ocp/composer.lock
          body: |
            Auto-generated update of [nextcloud/ocp](https://github.com/nextcloud-deps/ocp/) dependency
          labels: |
            dependencies
