# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

# TODO: Remove this after a grace period of 6 months to give everyone the chance to remove the workflow
# TODO: To be removed mid 2027.
name: No-op please remove this workflow

on: pull_request

permissions:
  contents: none

concurrency:
  group: update-nextcloud-ocp-approve-merge-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  auto-approve-merge:
    runs-on: ubuntu-latest-low
    if: always()

    # This is the summary, we just avoid to rename it so that branch protection rules still match
    name: auto-approve-merge

    steps:
      - name: No-op please remove this workflow
        run: echo "Approve and auto-merge has been folded into update-nextcloud-ocp.yml / update-nextcloud-ocp-matrix.yml, please remove this file"; exit 1;
